# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: namespace gimite
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gimite.github.io" # the base hostname & protocol for your site
twitter_username: gimite
github_username:  gimite
google_analytics: UA-573829-2

# Build settings
markdown: kramdown
